export const UI_CONTENT = {
  SYSTEM: {
    WARMUP_TOAST: "🌴 Server is waking up... first load may take ~30 seconds.",
  },
  LOADING: {
    TEXT_CHARS: ['C', 'o', 'c', 'o', 'n', 'u', 't'],
    SUBTITLE: "Waking up our culinary AI...",
  },
  HEADER: {
    TITLE: 'Order your favourite food here',
    DESCRIPTION: 'Choose from a diverse menu featuring a delectable array of dishes crafted with the finest ingredients and culinary expertise. Our mission is to satisfy your cravings and elevate your dining experience, one delicious meal at a time.',
    BUTTON_TEXT: 'View Menu',
  },
  FOOTER: {
    BRAND: 'Coconut',
    MISSION_STATEMENT: "Coconut is a passion project by a solo independent developer dedicated to modernizing the digital dining experience. Built with precision, fueled by coffee.",
    DESCRIPTION: "Thank you for choosing Coconut for your culinary cravings! We're dedicated to bringing you a delightful dining experience with every order. Whether it's a quick bite or a sumptuous feast, we're here to satisfy your hunger.",
    COMPANY_TITLE: 'COMPANY',
    GET_IN_TOUCH_TITLE: 'Get in Touch',
    RESOURCES_TITLE: 'Resources',
    NAVIGATION_TITLE: 'Navigation',
    NEWSLETTER_DESC: 'Have feedback or want to collaborate?',
    NEWSLETTER_PLACEHOLDER: 'Enter email...',
    QUICK_LINKS: ['Home', 'About us', 'Delivery', 'Privacy policy'],
    SOCIAL_TOAST: "We're currently setting up our official social channels. Stay tuned for the grand opening!",
    DEV_CREDIT_TOAST: "Crafted with ❤️ by a solo dev Prabodhan Aka Babul",
    DELIVERY_DISCLAIMER_TOAST: "Note: Coconut is currently under construction. No real food is delivered yet!",
    PRIVACY_POLICY_TOAST: "Open for all, fun for all. Your curiosity is welcome here!",
    TERMS_TOAST: "Feel free to explore, test, and play around with the application.",
    COPYRIGHT_TEXT: (year: number) => `Copyright ${year} © coconut.com`,
    MADE_WITH_TEXT: 'for the community',
    CONTACT: {
      PHONE: '+91 1234567890',
      EMAIL: 'contact@coconut.com',
    },
  },
  CART: {
    TITLE: 'Your Cart',
    EMPTY_MESSAGE: 'Your cart is completely empty.',
    PROMO_CODE_PROMPT: 'If you have a promo code, enter it here',
    CHECKOUT_BUTTON: 'PROCEED TO CHECKOUT',
  },
  PLACE_ORDER: {
    TITLE: 'Delivery Information',
    PHONE_PLACEHOLDER: 'Phone Number',
    ZIP_PLACEHOLDER: 'Zip Code',
    TOTAL_HEADER: 'Cart Totals',
    PAYMENT_BUTTON: 'PROCEED TO PAYMENT'
  },
  EXPLORE_MENU: {
    TITLE: 'Explore our menu',
    DESCRIPTION: 'Choose from a diverse menu featuring a delectable array of dishes. Our mission is to satisfy your cravings and elevate your dining experience.',
    ALL_FILTER: 'All',
  },
  APP_DOWNLOAD: {
    TEXT: 'For Better Experience Download Coconut App',
    COMING_SOON_TITLE: 'Coming Soon',
    COMING_SOON_SUBTITLE: "Our mobile applications are currently under development. \nWe're building something extraordinary for you.",
    NOTIFY_PLACEHOLDER: 'Enter your email for early access',
    NOTIFY_BTN: 'Notify Me',
    SUCCESS_TITLE: "✨ You're on the list!",
    SUCCESS_SUB: "We'll notify you as soon as we launch.",
  },
  FOOD_DISPLAY: {
    TITLE: 'Exclusive Delights',
  },
  NAVBAR: {
    LOGO_PREFIX: 'C',
    LOGO_EXPANDED: 'oconut',
    HOME: 'Home',
    MENU: 'Menu',
    MOBILE_APP: 'Mobile App',
    CONTACT_US: 'Contact Us',
    SIGN_IN: 'Sign In',
    PROFILE: 'Profile',
    ORDERS: 'Orders',
    LOGOUT: 'Logout',
  },
  LOGIN: {
    SIGN_UP_TITLE: 'Sign Up',
    LOGIN_TITLE: 'Login',
    NAME_PLACEHOLDER: 'Your name',
    EMAIL_PLACEHOLDER: 'Your email',
    PASSWORD_PLACEHOLDER: 'Password',
    CREATE_ACCOUNT_BTN: 'Create account',
    LOGIN_BTN: 'Login',
    TERMS_AGREEMENT: 'By continuing, I agree to the terms of use & privacy policy.',
    CREATE_NEW_PROMPT: 'Create a new account?',
    ALREADY_HAVE_PROMPT: 'Already have an account?',
    CLICK_HERE: 'Click here',
    LOGIN_HERE: 'Login here',
  },
  MY_ORDERS: {
    TITLE: 'My Orders',
    NO_ORDERS: 'No orders found',
    TRACK_ORDER_BTN: 'Track Order',
    ITEMS_PREFIX: 'Items: ',
  },
  PROFILE: {
    TITLE: 'Edit Profile',
    NAME_LABEL: 'Name',
    NAME_PLACEHOLDER: 'Your Name',
    EMAIL_LABEL: 'Email (Cannot be changed)',
    EMAIL_PLACEHOLDER: 'Your Email',
    PASSWORD_LABEL: 'New Password (Optional)',
    PASSWORD_PLACEHOLDER: 'Leave blank to keep current',
    UPDATE_BUTTON: 'Update Profile',
  },
  AI_CHAT: {
    TITLE: 'What can I help you order?',
    DESCRIPTION: 'Describe the coconut dish or meal combo you crave, and our AI will fetch the perfect menu recommendations for you.',
    PLACEHOLDER: "I'm craving a spicy coconut curry bowl...",
    ATTACH_TOOLTIP: 'Attach Image',
    LOADING_MESSAGE: 'Chef AI is analyzing ingredients...',
    ERROR_MESSAGE: 'Oops... my culinary AI circuits are a bit overloaded. Please try again.',
    GENERIC_ERROR: "I couldn't process that request right now.",
  }
};
